global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'federate'
    scrape_interval: 5s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job=~"morty_.*"}'
    static_configs:
      - targets:
          - 'prometheus:9091'
          - 'prometheus3:9093'

  - job_name: 'pushgateway'
    scrape_interval: 500ms
    honor_labels: true
    static_configs:
      - targets:
          - 'pushgateway:9191'
          - 'pushgateway2:9192'
          - 'pushgateway3:9193'