name: Add coverage to PR

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew jacocoTestReport > logs.txt

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs.txt

      - name: PR comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello world ! :wave: